
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Actions
 */
public class questions extends javax.swing.JFrame {

    /**
     * Creates new form questions
     */
    public questions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_examnresult = new javax.swing.JMenu();
        jMenu_question1 = new javax.swing.JMenu();
        jMenu_question2 = new javax.swing.JMenu();
        jMenu_question3 = new javax.swing.JMenu();
        jMenu_question4 = new javax.swing.JMenu();
        jMenu_question5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(1281, 721));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(1281, 721));

        jMenu_examnresult.setIcon(new javax.swing.ImageIcon("E:\\ANIK\\multiple-quiz-management-system\\src\\icons\\Favorites\\Favorites_48x48.png")); // NOI18N
        jMenu_examnresult.setText("Exam & result");
        jMenuBar1.add(jMenu_examnresult);

        jMenu_question1.setIcon(new javax.swing.ImageIcon("E:\\ANIK\\multiple-quiz-management-system\\src\\icons\\Previous\\Previous_48x48.png")); // NOI18N
        jMenu_question1.setText("Question1");
        jMenu_question1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_question1MouseClicked(evt);
            }
        });
        jMenu_question1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_question1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_question1);

        jMenu_question2.setText("Question2");
        jMenu_question2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_question2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu_question2);

        jMenu_question3.setText("Question3");
        jMenuBar1.add(jMenu_question3);

        jMenu_question4.setText("Question4");
        jMenuBar1.add(jMenu_question4);

        jMenu_question5.setText("Question5");
        jMenuBar1.add(jMenu_question5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_question2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_question2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_question2MouseClicked

    private void jMenu_question1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_question1ActionPerformed
        question1 rgf= new question1();  
        rgf.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_question1ActionPerformed

    private void jMenu_question1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_question1MouseClicked
        question1 rgf= new question1();  
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jMenu_question1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_examnresult;
    private javax.swing.JMenu jMenu_question1;
    private javax.swing.JMenu jMenu_question2;
    private javax.swing.JMenu jMenu_question3;
    private javax.swing.JMenu jMenu_question4;
    private javax.swing.JMenu jMenu_question5;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
